title: <p align="center"> Naseemuddin </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://github.com/MohdNaseem82">GitHub</a>
  
  <br>   
  I'm working on  Spark, Machine learning & Financial derivatives.
  Also handing the Big Data from real-time Ad call data.
  Working in Swedbank for 3 years.
  <br>
  </p>



theme: jekyll-theme-minimal
